### PR TITLE
Unity 4.0.1 / .NET 4.5 Upgrade

### PR DESCRIPTION
**Pull request by issafram**
Solves Issue #20.

### CODE REVIEW

**Comment by darrencauthon** [comment]
Wow, this is great.

Was it really this easy?  I can't remember the details, but it seemed that when I upgrade to Unity 3 way-back-when, the extensions that AutoMoq depends on stopped working.  I'm looking at your changes, though, and I don't see where you had to upgrade anything.  But the tests are passing, so... it should be good!

I'll use this to publish an AutoMoq 2.0, resetting the dependencies to Unity 2.0 and the latest Moq.  Any users who depend on the older Unity can stay < 2.0.

Thank you!!

**Comment by issafram** [comment]
> I'll use this to publish an AutoMoq 2.0, resetting the dependencies to Unity 2.0 and the latest Moq. Any users who depend on the older Unity can stay < 2.0.

I hope you meant **Unity 4.X**.  But yea, the change was easy.  

I use AutoMoq for almost every project.  It is a great library.  But I also use other libraries that use a newer version of Unity and the Microsoft Patterns & Practices team changed the PublicKeyToken so it is an all or none with the version of Unity.  2 vs 4.

**Comment by darrencauthon** [comment]
> I hope you meant Unity 4.X. But yea, the change was easy.

Yup!  Sorry, it's still early morning for me. :smile:

Part of me wants to go back and find out what the problem was with my own Unity upgrade, but... the other part of me wants to ask no questions, merge, and push!  

I'll note here when the release is made.  Thanks again!

**Comment by darrencauthon** [comment]
It's coming...

**Pull request merged**
