### PR TITLE
Upgrade solution to .Net Core 2.0

### PR DESCRIPTION
**Pull request by rickvi1**
Replaced Nunit with Xunit
Renamed some files

### CODE REVIEW

**Comment by rickvi1** [comment]
Because we really wanted a .Net Core2.0 version of automoq, I converted the project and unit tests to a .Net Core 2.0 solution. Everything is tested.

I hope you can complete te pull request soon!

**Comment by rickvi1** [comment]
This .Net Core 2.0 version is tested in actual unit tests, and works fine.

**Comment by chazt3n** [comment]
Is this going to be merged in?

**Comment by PandaWood** [comment]
Just a friendly interjection, I think replacing all the tests with a different framework should be separated into a different PR. 
Also moving to .NET Core 2.0 is not just a simple "upgrade". For one, it would prevent me from using this library as I'm bound to an earlier .NET Framework version. So is there support back to .NET4.5.2 (currently the oldest supported version) ?

**Pull request closed without merging**
